spring:
  data:
    mongodb:
      host: mongodb
      port: 27017
      database: productapp
      username: root
      password: password
      authentication-database: admin
      repositories:
        enabled: true
  application:
    name: productapp

server:
  port: 8086

logging:
  level:
    org:
    springframework:
      data:
        mongodb:
          repository:
            query: debug
          core:
            repository:
              query: debug

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
    health:
      enabled: true
    prometheus:
      enabled: true
    metrics:
      enabled: true

  info:
    env:
      enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  tracing:
    sampling:
      probability: 1.0

#Swagger Docs
springdoc:
  api-docs:
    path: api/v1/products/v3/api-docs
  swagger-ui:
    path: /swagger-ui.html