spring:
  application:
    name: gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000/realms/ShoppingApplication
  cloud:
    gateway:
      routes:
#        Order Service
        - id: order-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/orders/**
          filters:
            - name: CircuitBreaker
              args:
                name: orderCircuitBreaker
                fallbackUri: forward:/fallbackRoute
#        Product Service
        - id: product-service
          uri: http://localhost:8080
          predicates:
            - Path=/api/v1/products/**
          filters:
            - name: CircuitBreaker
              args:
                name: productCircuitBreaker
                fallbackUri: forward:/fallbackRoute
#        Inventory Service
        - id: inventory-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/inventory/**
          filters:
            - name: CircuitBreaker
              args:
                name: productCircuitBreaker
                fallbackUri: forward:/fallbackRoute
#        Review Service
        - id: review-service
          uri: http://localhost:8085
          predicates:
            - Path=/api/v1/reviews/**
          filters:
            - name: CircuitBreaker
              args:
                name: productCircuitBreaker
                fallbackUri: forward:/fallbackRoute

server:
  port: 8084

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
    health:
      enabled: true
  info:
    env:
      enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: orderapp
        url: /api/v1/orders/v3/api-docs
      - name: productapp
        url: /api/v1/products/v3/api-docs
      - name: inventoryapp
        url: /api/v1/inventory/v3/api-docs
      - name: reviews
        url: /api/v1/reviews/v3/api-docs