spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: productapp
      repositories:
        enabled: true
  application:
    name: inventoryapp

server:
  port: 8082

logging:
  level:
    org:
    springframework:
      data:
        mongodb:
          repository:
            query: debug
          core:
            repository:
              query: debug

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
    health:
      enabled: true
  info:
    env:
      enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

#Swagger Docs
springdoc:
  api-docs:
    path: api/v1/inventory/v3/api-docs
  swagger-ui:
    path: /swagger-ui.html