spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: productapp
      repositories:
        enabled: true
  application:
    name: inventoryapp

server:
  port: 8090

logging:
  level:
    org:
    springframework:
      data:
        mongodb:
          repository:
            query: debug
          core:
            repository:
              query: debug